name: staging
on: [push]

jobs:
  staging:
    runs-on: ubuntu-latest
    name: only for stage
    steps:
      - name: Get Pokemon name
        uses: ibrahimejaz/actiontesting@main
        id: pokemon
        with:
          pokemon_id: 150
      - name: Get the pokemon
        run: echo "${{ steps.pokemon.outputs.pokemon_name }} attack"
